### ISSUE TITLE
How to set auth token for authenticated pages?

### ISSUE THREAD

**Issue by li5tun** [nolanlawson/fuite#10]
how to provide auth token, or username/pw for all of the pages, when I run it with CLI

**Comment by nolanlawson** [comment]
You can extend the default scenario with your custom `setup` function using instructions here: https://github.com/nolanlawson/fuite#extending-the-default-scenario

And then define how you want to log in. Once you define this scenario file, you can run it from the CLI as described here: https://github.com/nolanlawson/fuite#scenarios

**Comment by nolanlawson** [comment]
Update: there is now a `--setup` option to make this simpler. https://github.com/nolanlawson/fuite/blob/master/README.md#setup

To set a cookie, you would probably need to use Puppeteer's [`page.setCookie`](https://pptr.dev/#?product=Puppeteer&version=v13.0.0&show=api-pagesetcookiecookies).

**Comment by nolanlawson** [comment]
Closing as this should be handled by the `--setup` option. Please reopen if I'm incorrect.

**Comment by andreasvirkus** [comment]
Sorry, to clarify - should the `--setup` option currently log the user in _and then_ visit the links that it finds after logging in? Or should we extend the default scenario for that to happen?
https://github.com/nolanlawson/fuite#extending-the-default-scenario

I thought that using `--setup` would automatically already extend the default scenario, but atm fuite still only visits the links on my login page (e.g. register and reset password)

**Comment by nolanlawson** [comment]
> Sorry, to clarify - should the `--setup` option currently log the user in and then visit the links that it finds after logging in?

Yes, exactly. Links are not crawled until after the setup logic has run. If it's only finding links on the login page, then perhaps the setup script is not running? Or it's not waiting long enough for the links to be visible?
