### ISSUE TITLE
Map.prototype.size incompatible receiver

### ISSUE THREAD

**Issue by Manubi** [nolanlawson/fuite#17]
<img width="1478" alt="CleanShot 2021-12-20 at 13 45 50@2x" src="https://user-images.githubusercontent.com/20935138/146769285-d17fb927-2584-4571-9354-d5a89657e33c.png">
Got this error on every page.... 

Does anyone know whats going on? 
Thanks!

**Comment by nolanlawson** [comment]
When you type `window.Map.toString()` in the DevTools console, do you see

```
"function Map() {
    [native code]
}"
```

?

If not, there may be a custom Map implementation (or polyfill) on the page. Maybe fuite should just ignore errors if it calls `.size` on something and it throws an error.

**Comment by nolanlawson** [comment]
Alternatively, is anything in your code extending Map?

```js
class MyCustomMap extends Map {
}
```

?

**Comment by nolanlawson** [comment]
I can repro using these steps: https://github.com/josdejong/mathjs/issues/2265#issuecomment-869150314

```js
const m = new Map()
const n = Object.create(m)
n.has('a')
```
