### ISSUE TITLE
Get an error when trying to run 

### ISSUE THREAD

**Issue by budarin** [nolanlawson/fuite#24]
Try to run 
`npx fuite <https://example.com>`

the error:
`cb.apply is not a function`

**Comment by nolanlawson** [comment]
Hi, I can't seem to reproduce the bug. Could you please provide:

1. Your OS
2. Your Node version
2. The URL you're testing (if possible)
3. Any more stack information? I don't know where `cb.apply` is coming from

Thanks!

**Comment by budarin** [comment]
OS: MacOS & Windows 10
Node version: v17.0.1
The URL you're testing (if possible): local project

[2021-12-28T00_38_44_132Z-debug.log](https://github.com/nolanlawson/fuite/files/7782134/2021-12-28T00_38_44_132Z-debug.log)

**Comment by nolanlawson** [comment]
Ah I see, it seems to be failing during the `npm install` step:

```
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at /Users/user/.config/yarn/global/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (node:fs:199:5)
```

Possibly this is due to a new Node v17 incompatibility or the `graceful-fs` package. I found a similar issue here: https://github.com/nodejs/help/issues/2874

I'd recommend trying Node 16, and clearing out your npm cache with `npm cache clean --force` and then try again. Or take a look at the thread above and see if that helps. :slightly_smiling_face:

**Comment by nolanlawson** [comment]
BTW I'm using Ubuntu 20.04 and I cannot repro, even using Node 17 and even using `npx fuite`.

**Comment by budarin** [comment]
have full reinstalled node with 16.3.1 version 

```log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/user/.nvm/versions/node/v16.13.1/bin/node',
1 verbose cli   '/Users/user/.config/yarn/global/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'fuite@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/user/.npm/_npx/53593',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v16.13.1
4 verbose npm-session a6c9683e9cf4d8df
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/fuite 978ms
8 http fetch GET 200 https://registry.npmjs.org/fuite/-/fuite-1.2.0.tgz 48ms
9 silly pacote tag manifest for fuite@latest fetched in 1067ms
10 verbose stack TypeError: cb.apply is not a function
10 verbose stack     at /Users/user/.config/yarn/global/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
10 verbose stack     at FSReqCallback.oncomplete (node:fs:199:5)
11 verbose cwd /Users/user
12 verbose Darwin 21.1.0
13 verbose argv "/Users/user/.nvm/versions/node/v16.13.1/bin/node" "/Users/user/.config/yarn/global/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "fuite@latest" "--global" "--prefix" "/Users/user/.npm/_npx/53593" "--loglevel" "error" "--json"
14 verbose node v16.13.1
15 verbose npm  v5.1.0
16 error cb.apply is not a function
17 verbose exit [ 1, true ]
```

**Comment by budarin** [comment]
it runs locally but with the error on every <a> tag

```
URL       : https://web_app.localhost/
Scenario  : Default
Iterations: 7 (Default)

TEST RESULTS

--------------------

Test         : Go to /page1 and back
Failed       : Element a[href="/page1"] is not clickable or is not an in-page SPA navigation 
element.click is not a function
TypeError: Element a[href="/page1"] is not clickable or is not an in-page SPA navigation 
element.click is not a function

Test         : Go to /page2 and back
Failed       : Element a[href="/page2"] is not clickable or is not an in-page SPA navigation 
element.click is not a function
TypeError: Element a[href="/page2"] is not clickable or is not an in-page SPA navigation 
element.click is not a function

...
```

![image](https://user-images.githubusercontent.com/8055157/147522633-2145a163-c51d-44ae-ae5d-c00e1e787f5a.png)

**Comment by nolanlawson** [comment]
Yeah that's the same as #11. It probably means that the link is not really an SPA link; i.e. clicking on it leaks to another page in a multi-page app.

If you have a live repro then I can verify. When I run `npx fuite https://reactrouter.com/` I don't see the same error, even though presumably that website uses react-router.

**Comment by budarin** [comment]
links are clickable and lead to another route in app
but how to test such applications - there are about 50% of all sites with such type of application.

**Comment by nolanlawson** [comment]
Without a live repro, I'm not sure what the issue is. Are these SPA navigations or MPA navigations? Are the links hidden or something? (e.g. `display: none`)

If these are MPA navigations, then almost certainly there is no leak and you don't need to use fuite, which is designed for 
SPAs. :slightly_smiling_face:

**Comment by budarin** [comment]
This is an SPA with visible and clickable links -let's watch the video

**Comment by nolanlawson** [comment]
SPAs should work. The video doesn't really illustrate to me what the problem is.

Have you tested `fuite` on some other React-based websites, like reactjs.org or gatsbyjs.com ? Last I tested, it works on those sites.

nvm shouldn't make a difference; it's just a way to switch between different Node versions.

**Comment by budarin** [comment]
> nvm shouldn't make a difference; it's just a way to switch between different Node versions.
this all sounds good in theory, but in practice it doesn't work for me in macOS or Windows

**Comment by nolanlawson** [comment]
Based on your description, it sounds like the issue is the website and not your OS or Node version.

```
TypeError: Element a[href="/page1"] is not clickable or is not an in-page SPA navigation 
element.click is not a function
```

Basically this means "`fuite` found a link on the page, but it tried to click it and press the back button and repeat, and at some point the element disappeared or became invisible."

Maybe the back button does not work correctly in the app? Just guessing here.

**Comment by budarin** [comment]
For me its unclear how '<a>' could be unclickable.

Every link in our app leads to a new route which is loadable component wrapped into suspend component

are you clicking too fast?
I don't have any more assumptions, but the links in the application are working and the application responds adequately to the Back button

**Comment by nolanlawson** [comment]
The default scenario has some filtering to try to sniff whether a link opens in a new tab or is invisible:

https://github.com/nolanlawson/fuite/blob/eefd3aaf5a436670303d27dbcba6b4a942337a80/src/defaultScenario.js#L22-L29

It also tries to wait for the page to become idle (both in terms of CPU and network):

https://github.com/nolanlawson/fuite/blob/eefd3aaf5a436670303d27dbcba6b4a942337a80/src/defaultScenario.js#L84-L89

If you modify [this line](https://github.com/nolanlawson/fuite/blob/eefd3aaf5a436670303d27dbcba6b4a942337a80/src/defaultScenario.js#L24) to add a `debugger` statement beforehand (e.g. with a local `fuite` install, not a global one), and if you run:

```
NODE_OPTIONS=inspect-brk ./node_modules/.bin/fuite --debug <your website>
```

(See README for instructions on using `chrome:inspect` to inspect Node)

...and then open the Chromium DevTools when the window pops up, then you will be able to debug to see why the element is not considered visible by `fuite`.

**Comment by budarin** [comment]
I may have discovered a potential problem: our application is waiting for the installation of a service worker and only after that react hydrate starts, although all the markup comes from the server and fuite, unaware of the presence of waiting for the installation of a service worker, starts working with a page that is not yet "live"

**Comment by nolanlawson** [comment]
That's interesting. I wonder if I can make the default scenario wait for service worker installations. Or detect splash screens somehow? (Not sure this is possible.)

Alternatively, you can use the `--setup` option to make it wait for the splash screen to disappear. For example, you can have it wait for some condition to be true:

```js
export async function setup (page) {
  await page.waitForSelector('#elementThatShouldBeVisible')
}
```

**Comment by budarin** [comment]
Yes - this solves the problem, thank you for your patience in solving the issue.

**Comment by trollepierre** [comment]
Hello, 
I reproduced that problem today.
Then I discover I was using Node 12. So I use Node 16. Then it worked.
(i leave this trick for posterity 😘  )
