### ISSUE TITLE
Support output for JS API

### ISSUE THREAD

**Issue by andreasvirkus** [nolanlawson/fuite#75]
Hello again! 👋 

Would you accept a PR to add `output` as an option to the `findLeaks` options similarly to what the CLI supports today, so I as a user wouldn't have to handle dumping the output to a JSON file?

**Comment by nolanlawson** [comment]
@andreasvirkus Can you explain more what the value of the explicit `output` API would be? I figured it's pretty easy right now to dump to a JSON file:

```js
import { appendFileSync } from 'node:fs';
for await (const result of results) {
  appendFileSync('out.json', JSON.stringify(result, null, 2), 'utf-8')
}
```

**Comment by nolanlawson** [comment]
Closing, please reopen if this is still an issue for you!
