### ISSUE TITLE
How to create an isolated navigation scenario?

### ISSUE THREAD

**Issue by andreasvirkus** [nolanlawson/fuite#76]
Hi,

I can't seem to figure out how could I tell fuite to only perform a single navigation in the whole test suite? The default `iteration` logic suits me just fine, but when I define a single link in my own custom `createTests`:

```js
export async function createTests(_page) {
  return [
    {
      data: {
        href: `/settings/profile/general`,
        fullHref: `https://localhost:8888/settings/profile/general`,
      },
      description: `Go to Profile settings and back`
    }
  ]
}
```

Then fuite just exits with an empty error:
```json
{
    "test": {
        "data": {
            "href": "/settings/profile/general",
            "fullHref": "https://localhost:8888/settings/profile/general"
        },
        "description": "Go to Profile settings and back"
    },
    "result": {
        "failed": true,
        "error": {}
    }
}
```

This would be useful for when I've already detected a leaking scenario manually and would like to use Fuite less as a discovery tool but more for its friendly debugging/logs purposes.

**Comment by andreasvirkus** [comment]
If I try to overwrite the iteration itself with specific selectors to my custom scenario, it still fails to interact with these elements (even though these selectors work fine when running manually from the console 🤔)

```js
export async function iteration(page, { href }) {
  await waitForIdle(page)
  await page.click('[data-testid=q-avatar]')
  await page.click(`a[href=${JSON.stringify(href)}]`)
  await waitForIdle(page)
  await page.goBack()
  await waitForIdle(page)
}
```

**Comment by nolanlawson** [comment]
> I can't seem to figure out how could I tell fuite to only perform a single navigation in the whole test suite?

> This would be useful for when I've already detected a leaking scenario manually and would like to use Fuite less as a discovery tool but more for its friendly debugging/logs purposes.

I'm not sure Fuite is really designed for what you're trying to do? Or at least, I don't understand this use case.

You can certainly tell fuite to do its initial navigation (which is what it does with the `url` you pass in) and then define what to do after that as part of your `iteration`. Or you could even pass in `about:blank` or something as the "initial" URL and then do whatever you want in the `iteration` step.

**Comment by nolanlawson** [comment]
Closing, please reopen if this is still an issue.

BTW if your selectors are not matching, you may want to use `--debug` mode to try to figure out why the selectors are not matching. Usually it is a timing issue or something.
