### ISSUE TITLE
JS API: debug setting not respected

### ISSUE THREAD

**Issue by andreasvirkus** [nolanlawson/fuite#77]
It seems that using the debug setting doesn't work properly with the JS API, as Puppeteer is closed immediately after the iterations end.

Here's my `fuite.mjs` file:
```js
import { defaultScenario, findLeaks } from 'fuite'
import { createTests, setup, iteration } from './conversationsToSettings.scenario.mjs'

const myScenario = {
  ...defaultScenario,
  createTests,
  setup,
  iteration
}

let log = []

for await (const result of findLeaks('https://localhost:8888', {
  scenario: myScenario,
  iterations: 7,
  heapsnapshot: false,
  debug: process.env.DEBUG || false,
  progress: true,
})) {
  const entry = JSON.stringify(result, null, 2)
  // console.log(entry)
  log.push(entry)
}
```

And I'm running it like this
```sh
DEBUG=true node fuite.mjs
```

**Comment by nolanlawson** [comment]
Hm, I think maybe you are missing the `node --inspect-brk`? You're definitely passing in `debug` correctly – the CLI does the same thing: 

https://github.com/nolanlawson/fuite/blob/4e57dd973d458d93af5d62802c679ed25617dd43/src/cli.js#L83-L91
