### ISSUE TITLE
How can I analyze the test result?

### ISSUE THREAD

**Issue by oleksandr-dukhovnyy** [nolanlawson/fuite#81]
I used this tool to handle a production project. SPA with dozens of routes, for `35,000 code terms`.
I just dropped the main page: npx fuite `https://app.com -o res.json`.
About timeout (43 links checked, 7 iterations) gave me a `res.json` file...
But it contains `7,987,017` lines and is about `200 MB` in size.

As far as I understand, there is a detailed count for each transition/test.

That's cool, but I'd like to get a simple nameplate:
```
+------------------------+--------+
| ROUTE                  | LEAK   |
+------------------------+--------+
| https://app.com/about  | 0.3 KB |
| https://app.com/shop   | 10 MB  |
| https://app.com/my     | 0 B    |
+------------------------+--------+
```

But when I already understand that the transition to `/shop' is problematic, then I already want to learn the smaller subtleties.

Question 0: **How can I get such a plate?**
Question 1: **How can I analyze the data already received? Is there software for this?**

**Comment by nolanlawson** [comment]
The JSON format is designed to be consumable by whatever tool you want. If you want to simplify the results, you can filter the JSON file to include only the data you want to see.

**Comment by nolanlawson** [comment]
Closing as this seems like a question rather than an issue.

One other way you could simplify the results is to create a custom scenario extending the default scenario (see the README for how to do this) and then filter out the test cases so you're only analyzing 1 at a time. This may make it quicker to track down individual leaks.
