### ISSUE TITLE
Why are the results different every time

### ISSUE THREAD

**Issue by lidakai** [nolanlawson/fuite#84]
![image](https://github.com/nolanlawson/fuite/assets/23355645/8d8d8419-85dd-48bc-ad84-60cea3736dee)
![image](https://github.com/nolanlawson/fuite/assets/23355645/27f083e4-a25b-46e9-875b-b074e1fbda7c)
![image](https://github.com/nolanlawson/fuite/assets/23355645/c4c04f54-1e99-4717-8e91-d7b0b4da2a83)

您好，打扰一下，

请问，每次测试结果都不一样，这是为什么？期间没有更改任何代码。

**Comment by nolanlawson** [comment]
`Object` is probably a false positive. Or fuite can't figure out the unique class name for whatever is leaking.

You might try getting a second opinion from another leak tool like memlab: https://www.npmjs.com/package/memlab

**Comment by nolanlawson** [comment]
Hope that helps! fuite is not a perfect tool, so sometimes you will have to do some manual debugging to figure these things out.
