### ISSUE TITLE
Update Puppeteer to 22 so fuite can run on Linux machines

### ISSUE THREAD

**Issue by MattiasMartens** [nolanlawson/fuite#96]
An issue has come up here with Puppeteer: https://github.com/puppeteer/puppeteer/issues/11967

In effect, the problem is that older versions of Puppeteer, such as 21 which the latest version of fuite depends on, don't work on Linux environments anymore (or at least not consistently) because the URL it specifies to download a chrome runtime from is being phased out.

Updating the version of puppeteer to the latest will fix this problem.

**Comment by nolanlawson** [comment]
Thanks for reporting, should be fixed in v4.0.5
